#kelp.packaging.add:
#    path: /packaging/add/{id}
#    controller: App\Controller\PackagingController::createAction

kelp.packaging.list:
    path: /packaging/list/{page}
    controller: App\Controller\PackagingController::listAction
    defaults:
        page: 1
    requirements:
        page: '\d+'

kelp.packaging.edit:
    path: /packaging/edit/{id}
    controller: App\Controller\PackagingController::editAction
    requirements:
        id: '\d+'
